# Generated by Django 4.1.4 on 2023-09-28 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('weapon', models.CharField(max_length=20)),
                ('element', models.CharField(max_length=20)),
                ('ascension_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lv1', models.CharField(max_length=30)),
                ('lv2', models.CharField(max_length=30)),
                ('lv3', models.CharField(max_length=30)),
                ('lv4', models.CharField(max_length=30)),
                ('lv5', models.CharField(max_length=30)),
                ('lv6', models.CharField(max_length=30)),
                ('lv7', models.CharField(max_length=30)),
                ('lv8', models.CharField(max_length=30)),
                ('lv9', models.CharField(max_length=30)),
                ('lv10', models.CharField(max_length=30)),
                ('lv11', models.CharField(max_length=30)),
                ('lv12', models.CharField(max_length=30)),
                ('lv13', models.CharField(max_length=30)),
                ('lv14', models.CharField(max_length=30)),
                ('lv15', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CharSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='data.character')),
                ('moves', models.ManyToManyField(to='data.move')),
            ],
        ),
        migrations.CreateModel(
            name='CharNormAtk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normal_atk', to='data.character')),
                ('moves', models.ManyToManyField(to='data.move')),
            ],
        ),
        migrations.CreateModel(
            name='CharHP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lv1', models.CharField(max_length=20)),
                ('lv20', models.CharField(max_length=20)),
                ('lv20plus', models.CharField(max_length=20)),
                ('lv40', models.CharField(max_length=20)),
                ('lv40plus', models.CharField(max_length=20)),
                ('lv50', models.CharField(max_length=20)),
                ('lv50plus', models.CharField(max_length=20)),
                ('lv60', models.CharField(max_length=20)),
                ('lv60plus', models.CharField(max_length=20)),
                ('lv70', models.CharField(max_length=20)),
                ('lv70plus', models.CharField(max_length=20)),
                ('lv80', models.CharField(max_length=20)),
                ('lv80plus', models.CharField(max_length=20)),
                ('lv90', models.CharField(max_length=20)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hp', to='data.character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lv1', models.CharField(max_length=20)),
                ('lv20', models.CharField(max_length=20)),
                ('lv20plus', models.CharField(max_length=20)),
                ('lv40', models.CharField(max_length=20)),
                ('lv40plus', models.CharField(max_length=20)),
                ('lv50', models.CharField(max_length=20)),
                ('lv50plus', models.CharField(max_length=20)),
                ('lv60', models.CharField(max_length=20)),
                ('lv60plus', models.CharField(max_length=20)),
                ('lv70', models.CharField(max_length=20)),
                ('lv70plus', models.CharField(max_length=20)),
                ('lv80', models.CharField(max_length=20)),
                ('lv80plus', models.CharField(max_length=20)),
                ('lv90', models.CharField(max_length=20)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defense', to='data.character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharBurst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burst', to='data.character')),
                ('moves', models.ManyToManyField(to='data.move')),
            ],
        ),
        migrations.CreateModel(
            name='CharAtk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lv1', models.CharField(max_length=20)),
                ('lv20', models.CharField(max_length=20)),
                ('lv20plus', models.CharField(max_length=20)),
                ('lv40', models.CharField(max_length=20)),
                ('lv40plus', models.CharField(max_length=20)),
                ('lv50', models.CharField(max_length=20)),
                ('lv50plus', models.CharField(max_length=20)),
                ('lv60', models.CharField(max_length=20)),
                ('lv60plus', models.CharField(max_length=20)),
                ('lv70', models.CharField(max_length=20)),
                ('lv70plus', models.CharField(max_length=20)),
                ('lv80', models.CharField(max_length=20)),
                ('lv80plus', models.CharField(max_length=20)),
                ('lv90', models.CharField(max_length=20)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atk', to='data.character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AscensionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lv1', models.CharField(max_length=20)),
                ('lv20', models.CharField(max_length=20)),
                ('lv20plus', models.CharField(max_length=20)),
                ('lv40', models.CharField(max_length=20)),
                ('lv40plus', models.CharField(max_length=20)),
                ('lv50', models.CharField(max_length=20)),
                ('lv50plus', models.CharField(max_length=20)),
                ('lv60', models.CharField(max_length=20)),
                ('lv60plus', models.CharField(max_length=20)),
                ('lv70', models.CharField(max_length=20)),
                ('lv70plus', models.CharField(max_length=20)),
                ('lv80', models.CharField(max_length=20)),
                ('lv80plus', models.CharField(max_length=20)),
                ('lv90', models.CharField(max_length=20)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ascension_stat', to='data.character')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
