# Generated by Django 4.1.4 on 2023-09-29 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=200)),
                ('weapon_type', models.CharField(max_length=500)),
                ('substat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='charburst',
            name='name',
        ),
        migrations.RemoveField(
            model_name='charnormatk',
            name='name',
        ),
        migrations.RemoveField(
            model_name='charskill',
            name='name',
        ),
        migrations.CreateModel(
            name='WeaponSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lv1', models.CharField(max_length=20)),
                ('lv20', models.CharField(max_length=20)),
                ('lv20plus', models.CharField(max_length=20)),
                ('lv40', models.CharField(max_length=20)),
                ('lv40plus', models.CharField(max_length=20)),
                ('lv50', models.CharField(max_length=20)),
                ('lv50plus', models.CharField(max_length=20)),
                ('lv60', models.CharField(max_length=20)),
                ('lv60plus', models.CharField(max_length=20)),
                ('lv70', models.CharField(max_length=20)),
                ('lv70plus', models.CharField(max_length=20)),
                ('lv80', models.CharField(max_length=20)),
                ('lv80plus', models.CharField(max_length=20)),
                ('lv90', models.CharField(max_length=20)),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='data.weapon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponAtk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lv1', models.CharField(max_length=20)),
                ('lv20', models.CharField(max_length=20)),
                ('lv20plus', models.CharField(max_length=20)),
                ('lv40', models.CharField(max_length=20)),
                ('lv40plus', models.CharField(max_length=20)),
                ('lv50', models.CharField(max_length=20)),
                ('lv50plus', models.CharField(max_length=20)),
                ('lv60', models.CharField(max_length=20)),
                ('lv60plus', models.CharField(max_length=20)),
                ('lv70', models.CharField(max_length=20)),
                ('lv70plus', models.CharField(max_length=20)),
                ('lv80', models.CharField(max_length=20)),
                ('lv80plus', models.CharField(max_length=20)),
                ('lv90', models.CharField(max_length=20)),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atk', to='data.weapon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
