# Generated by Django 4.1.4 on 2023-05-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255, unique=True)),
                ('passive', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255, unique=True)),
                ('weapon', models.CharField(max_length=255)),
                ('element', models.CharField(max_length=255)),
                ('hp', models.JSONField()),
                ('atk', models.JSONField()),
                ('defense', models.JSONField()),
                ('critrate', models.JSONField()),
                ('critdmg', models.JSONField()),
                ('ascension', models.JSONField()),
                ('ascension_stat', models.CharField(max_length=255)),
                ('normal_atk', models.JSONField()),
                ('skill', models.JSONField()),
                ('burst', models.JSONField()),
                ('sprint', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=255)),
                ('atk', models.JSONField()),
                ('substat_name', models.CharField(blank=True, max_length=255, null=True)),
                ('substat_lv', models.JSONField(blank=True, null=True)),
                ('passive_stat', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
